### ISSUE TITLE
[Feat] 카테고리 관리 뷰 구현

### ISSUE THREAD

**Issue by mxinseo** [SMWU-Cookiee/Cookiee-Client-iOS#17]
## Issue
카테고리 관리 뷰 구현

## To-do
- [x] 카테고리 관리 페이지 연결
- [x] 카테고리 이름 편집 필드
- [x] 카테고리 색상 팔레트 모달 창
